name: Main CI

on:
  push:
    branches:
      - main
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn
        uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
